
package br.gov.infraero.siga.pen.client.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "interoperabilidadeException", targetNamespace = "http://pen.planejamento.gov.br/interoperabilidade/soap/v2")
public class InteroperabilidadeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InteroperabilidadeException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InteroperabilidadeException_Exception(String message, InteroperabilidadeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InteroperabilidadeException_Exception(String message, InteroperabilidadeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.gov.infraero.siga.pen.client.model.InteroperabilidadeException
     */
    public InteroperabilidadeException getFaultInfo() {
        return faultInfo;
    }

}
