
package br.gov.infraero.siga.pen.client.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InteroperabilidadePENService", targetNamespace = "http://pen.planejamento.gov.br/interoperabilidade/soap/v2", wsdlLocation = "file:/Users/tiagomeneses/Downloads/pen-client/wsdl_v2/interoperabilidade-pen-v2.wsdl")
public class InteroperabilidadePENService
    extends Service
{

    private final static URL INTEROPERABILIDADEPENSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTEROPERABILIDADEPENSERVICE_EXCEPTION;
    private final static QName INTEROPERABILIDADEPENSERVICE_QNAME = new QName("http://pen.planejamento.gov.br/interoperabilidade/soap/v2", "InteroperabilidadePENService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/tiagomeneses/Downloads/pen-client/wsdl_v2/interoperabilidade-pen-v2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEROPERABILIDADEPENSERVICE_WSDL_LOCATION = url;
        INTEROPERABILIDADEPENSERVICE_EXCEPTION = e;
    }

    public InteroperabilidadePENService() {
        super(__getWsdlLocation(), INTEROPERABILIDADEPENSERVICE_QNAME);
    }

    public InteroperabilidadePENService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEROPERABILIDADEPENSERVICE_QNAME, features);
    }

    public InteroperabilidadePENService(URL wsdlLocation) {
        super(wsdlLocation, INTEROPERABILIDADEPENSERVICE_QNAME);
    }

    public InteroperabilidadePENService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEROPERABILIDADEPENSERVICE_QNAME, features);
    }

    public InteroperabilidadePENService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InteroperabilidadePENService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InteroperabilidadePEN
     */
    @WebEndpoint(name = "InteroperabilidadePENPort")
    public InteroperabilidadePEN getInteroperabilidadePENPort() {
        return super.getPort(new QName("http://pen.planejamento.gov.br/interoperabilidade/soap/v2", "InteroperabilidadePENPort"), InteroperabilidadePEN.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InteroperabilidadePEN
     */
    @WebEndpoint(name = "InteroperabilidadePENPort")
    public InteroperabilidadePEN getInteroperabilidadePENPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pen.planejamento.gov.br/interoperabilidade/soap/v2", "InteroperabilidadePENPort"), InteroperabilidadePEN.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEROPERABILIDADEPENSERVICE_EXCEPTION!= null) {
            throw INTEROPERABILIDADEPENSERVICE_EXCEPTION;
        }
        return INTEROPERABILIDADEPENSERVICE_WSDL_LOCATION;
    }

}
