INSERT INTO CORPORATIVO.CP_MARCADOR (ID_MARCADOR,DESCR_MARCADOR,ID_FINALIDADE_MARCADOR,ORD_MARCADOR,GRUPO_MARCADOR,ID_LOTACAO_INI,DESCR_DETALHADA,ID_COR,ID_ICONE,HIS_ID_INI,HIS_DT_INI,HIS_IDC_INI,HIS_DT_FIM,HIS_IDC_FIM,HIS_ATIVO) VALUES
(2000,'Recebido Orgão Externo',1,2000,12,NULL,'Recebido do PEN',NULL,NULL,2000,NULL,NULL,NULL,NULL,1)
;
