INSERT INTO SIGA.EX_TIPO_MOVIMENTACAO (ID_TP_MOV,DESCR_TIPO_MOVIMENTACAO) VALUES
(80,'Tramite Envio PEN')
;
INSERT INTO SIGA.EX_TIPO_MOVIMENTACAO (ID_TP_MOV,DESCR_TIPO_MOVIMENTACAO) VALUES
(82,'Recibo de Recusa PEN')
;
INSERT INTO SIGA.EX_TIPO_MOVIMENTACAO (ID_TP_MOV,DESCR_TIPO_MOVIMENTACAO) VALUES
(84,'Recibo Envio PEN')
;
