INSERT INTO SIGA.EX_TIPO_MOVIMENTACAO (ID_TP_MOV,DESCR_TIPO_MOVIMENTACAO) VALUES
(81,'Tramite Recebimento PEN')
;
INSERT INTO SIGA.EX_TIPO_MOVIMENTACAO (ID_TP_MOV,DESCR_TIPO_MOVIMENTACAO) VALUES
(83,'Recibo de Tramite PEN')
;
